base_image: "anyscale/ray-ml:nightly-gpu"
env_vars: {}

post_build_cmds:
  - pip uninstall ray
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - HOROVOD_WITH_GLOO=1 HOROVOD_WITHOUT_MPI=1 HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITH_PYTORCH=1 pip3 install -U git+https://github.com/horovod/horovod.git